es.logger.level: WARN
rootLogger: ${es.logger.level}, console
logger:
  action: WARN
  com.amazonaws: WARN

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"